### PR TITLE
typo in install instructions

### PR DESCRIPTION
**Pull request by akkartik**

### CODE REVIEW

**Comment by mempko** [comment]
Thanks!

**Comment by akkartik** [comment]
I'm playing with it with some friends. This is awesome! I got it to build without problems. Ran into a segfault when I tried to install the file transfer app, but it worked for my friends (who were on the binary release) and works for me after I restart.

**Comment by mempko** [comment]
Thanks! 

Do you still have the segfault output by any chance?

Also OS, compiler, etc..

**Comment by akkartik** [comment]
I'll open another bug, fwiw. The output didn't seem to have anything interesting but I'll paste it in.

**Comment by mempko** [comment]
Great. Any output is better than no output. 

My goal is to have bug free software, so I try to keep my bug lists empty. So keep them coming :-)

**Pull request merged**
